-- MySQL Script generated by MySQL Workbench
-- Thu Feb  3 15:49:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `todos` ;

-- -----------------------------------------------------
-- Schema todos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todos` DEFAULT CHARACTER SET utf8 ;
USE `todos` ;

-- -----------------------------------------------------
-- Table `todos`.`todo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todos`.`todo` ;

CREATE TABLE IF NOT EXISTS `todos`.`todo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `done` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
